### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by Solido** [ibhavikmakwana/youtube_flutter_app#1]
Very nice startup.
I would just defend the case against round corners and shadows on the video.
You need to maximise the visibility of this portion.

**Comment by ibhavikmakwana** [comment]
Thank you @Solido  and I have got the same suggestion from so many, I have removed the extra round corners and removed the shadow too,
Will going to update it soon with some new screens.
Thanks for the suggestion :-)

**Comment by ibhavikmakwana** [comment]
Have update the UI and in detail view the shadow and rounded corner are removed.
In home screen decreased the  border radius and card elevation.
