### ISSUE TITLE
Pubspec.yaml reports an issue

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [ibhavikmakwana/youtube_flutter_app#2]
> "warning: The asset 'assets/images/' does not exist. (asset_does_not_exist at [youtube_flutter_app] pubspec.yaml:33)"

 I checked and the folder is there. I've had an issue with importing asset folders before. I'm not sure why it does this.

**Comment by ibhavikmakwana** [comment]
resolved in stable version of flutter
